# Generated by Django 4.2.8 on 2023-12-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_assistant_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
            ],
        ),
    ]
