# Generated by Django 4.2.8 on 2023-12-30 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_assistant_backend', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
